name = "discord-chunker"
main = "src/index.ts"
compatibility_date = "2025-01-01"

workers_dev = false
preview_urls = true

routes = [
  { pattern = "discord.git.ci", custom_domain = true }
]

[observability]
enabled = true
head_sampling_rate = 1  # 100% sampling (default)

[observability.logs]
invocation_logs = true  # Enable invocation logs (default)