name = "discord-chunker"
main = "src/index.ts"
compatibility_date = "2025-01-01"

workers_dev = false
preview_urls = true

routes = [
  { pattern = "discord.git.ci", custom_domain = true }
]

[assets]
directory = "./public"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
invocation_logs = true

[observability.traces]
enabled = true
